check-location:
  world: world
  x: 0
  y: 64
  z: 0
check-duration: 300
ban-reasons:
  - Признание
  - Уклон
  - Лив
  - Нурик
  - Оскорбление
  - Експенсив
  - Хит-боксы
  - Метеор
  - Инженчект-чит
  - Думсдей
ban-durations:
  Признание: 20d

default-ban-duration: 30d



message:
  no-command: "&7[&cCheck&7] &fВы не можете использовать команды во время проверки."
  no-lace: "&7[&cCheck&7] &fВы не можете двигаться во время проверки."
  leave: "&7[&cCheck&7] &fИгрок &c%player%&f вышел во время проверки."
  no-check: "&7[&cCheck&7] &fЭтого игрока нельзя вызывать на проверку!"
  no-two: "&7[&cCheck&7] &fЗаперши прошлую проверку, а потом начинай новую!"
  proverka: "&7[&cCheck&7] &fВы вызвали игрока &c%player%&f на проверку."
  succeful: "&7[&cCheck&7] &fВы прошли проверку!"
  time: "&7[&cCheck&7] &fВремя проверки вышло."